[package]
name = "better-git-branch"
version = "1.0.1"
authors = ["lachlan mcmillan <lachlanmcmillan@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.9"
termion = "1.5"
